//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGymTrivelloniBattaglioli.ServiceReferenceWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractDTO", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ContractDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Data_inizioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrezzoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data_inizio {
            get {
                return this.Data_inizioField;
            }
            set {
                if ((this.Data_inizioField.Equals(value) != true)) {
                    this.Data_inizioField = value;
                    this.RaisePropertyChanged("Data_inizio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Durata {
            get {
                return this.DurataField;
            }
            set {
                if ((this.DurataField.Equals(value) != true)) {
                    this.DurataField = value;
                    this.RaisePropertyChanged("Durata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Prezzo {
            get {
                return this.PrezzoField;
            }
            set {
                if ((this.PrezzoField.Equals(value) != true)) {
                    this.PrezzoField = value;
                    this.RaisePropertyChanged("Prezzo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codice_fiscaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime data_nascitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ruoloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sessoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codice_fiscale {
            get {
                return this.codice_fiscaleField;
            }
            set {
                if ((object.ReferenceEquals(this.codice_fiscaleField, value) != true)) {
                    this.codice_fiscaleField = value;
                    this.RaisePropertyChanged("codice_fiscale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.cognomeField, value) != true)) {
                    this.cognomeField = value;
                    this.RaisePropertyChanged("cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime data_nascita {
            get {
                return this.data_nascitaField;
            }
            set {
                if ((this.data_nascitaField.Equals(value) != true)) {
                    this.data_nascitaField = value;
                    this.RaisePropertyChanged("data_nascita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ruolo {
            get {
                return this.ruoloField;
            }
            set {
                if ((object.ReferenceEquals(this.ruoloField, value) != true)) {
                    this.ruoloField = value;
                    this.RaisePropertyChanged("ruolo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sesso {
            get {
                return this.sessoField;
            }
            set {
                if ((object.ReferenceEquals(this.sessoField, value) != true)) {
                    this.sessoField = value;
                    this.RaisePropertyChanged("sesso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchedaDTO", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class SchedaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGymTrivelloniBattaglioli.ServiceReferenceWCF.CaratteristicaEsercizioDTO[] Caratteristica_eserciziField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Data_inizioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGymTrivelloniBattaglioli.ServiceReferenceWCF.EsercizioDTO[] EserciziField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool In_usoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mail_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mail_trainerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitoloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGymTrivelloniBattaglioli.ServiceReferenceWCF.CaratteristicaEsercizioDTO[] Caratteristica_esercizi {
            get {
                return this.Caratteristica_eserciziField;
            }
            set {
                if ((object.ReferenceEquals(this.Caratteristica_eserciziField, value) != true)) {
                    this.Caratteristica_eserciziField = value;
                    this.RaisePropertyChanged("Caratteristica_esercizi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data_inizio {
            get {
                return this.Data_inizioField;
            }
            set {
                if ((this.Data_inizioField.Equals(value) != true)) {
                    this.Data_inizioField = value;
                    this.RaisePropertyChanged("Data_inizio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Durata {
            get {
                return this.DurataField;
            }
            set {
                if ((this.DurataField.Equals(value) != true)) {
                    this.DurataField = value;
                    this.RaisePropertyChanged("Durata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGymTrivelloniBattaglioli.ServiceReferenceWCF.EsercizioDTO[] Esercizi {
            get {
                return this.EserciziField;
            }
            set {
                if ((object.ReferenceEquals(this.EserciziField, value) != true)) {
                    this.EserciziField = value;
                    this.RaisePropertyChanged("Esercizi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool In_uso {
            get {
                return this.In_usoField;
            }
            set {
                if ((this.In_usoField.Equals(value) != true)) {
                    this.In_usoField = value;
                    this.RaisePropertyChanged("In_uso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail_cliente {
            get {
                return this.Mail_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Mail_clienteField, value) != true)) {
                    this.Mail_clienteField = value;
                    this.RaisePropertyChanged("Mail_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail_trainer {
            get {
                return this.Mail_trainerField;
            }
            set {
                if ((object.ReferenceEquals(this.Mail_trainerField, value) != true)) {
                    this.Mail_trainerField = value;
                    this.RaisePropertyChanged("Mail_trainer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titolo {
            get {
                return this.TitoloField;
            }
            set {
                if ((object.ReferenceEquals(this.TitoloField, value) != true)) {
                    this.TitoloField = value;
                    this.RaisePropertyChanged("Titolo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaratteristicaEsercizioDTO", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CaratteristicaEsercizioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Num_ripetizioniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan RecuperoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commento {
            get {
                return this.CommentoField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentoField, value) != true)) {
                    this.CommentoField = value;
                    this.RaisePropertyChanged("Commento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Num_ripetizioni {
            get {
                return this.Num_ripetizioniField;
            }
            set {
                if ((this.Num_ripetizioniField.Equals(value) != true)) {
                    this.Num_ripetizioniField = value;
                    this.RaisePropertyChanged("Num_ripetizioni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Recupero {
            get {
                return this.RecuperoField;
            }
            set {
                if ((this.RecuperoField.Equals(value) != true)) {
                    this.RecuperoField = value;
                    this.RaisePropertyChanged("Recupero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EsercizioDTO", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EsercizioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImmagineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Immagine {
            get {
                return this.ImmagineField;
            }
            set {
                if ((object.ReferenceEquals(this.ImmagineField, value) != true)) {
                    this.ImmagineField = value;
                    this.RaisePropertyChanged("Immagine");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWCF.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InserisciCliente", ReplyAction="http://tempuri.org/IService/InserisciClienteResponse")]
        bool InserisciCliente(string codice_fiscale, string nome, string cognome, string mail, string data_nascita, string telefono, string password, string sesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InserisciCliente", ReplyAction="http://tempuri.org/IService/InserisciClienteResponse")]
        System.Threading.Tasks.Task<bool> InserisciClienteAsync(string codice_fiscale, string nome, string cognome, string mail, string data_nascita, string telefono, string password, string sesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAvailableContracts", ReplyAction="http://tempuri.org/IService/GetAvailableContractsResponse")]
        WebGymTrivelloniBattaglioli.ServiceReferenceWCF.ContractDTO[] GetAvailableContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAvailableContracts", ReplyAction="http://tempuri.org/IService/GetAvailableContractsResponse")]
        System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.ContractDTO[]> GetAvailableContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddContractToClient", ReplyAction="http://tempuri.org/IService/AddContractToClientResponse")]
        bool AddContractToClient(int id, string codice_fiscale, string startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddContractToClient", ReplyAction="http://tempuri.org/IService/AddContractToClientResponse")]
        System.Threading.Tasks.Task<bool> AddContractToClientAsync(int id, string codice_fiscale, string startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CercaPersonalTrainerNelDB", ReplyAction="http://tempuri.org/IService/CercaPersonalTrainerNelDBResponse")]
        bool CercaPersonalTrainerNelDB(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CercaPersonalTrainerNelDB", ReplyAction="http://tempuri.org/IService/CercaPersonalTrainerNelDBResponse")]
        System.Threading.Tasks.Task<bool> CercaPersonalTrainerNelDBAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AlreadyRegistered", ReplyAction="http://tempuri.org/IService/AlreadyRegisteredResponse")]
        bool AlreadyRegistered(string codice_fiscale, string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AlreadyRegistered", ReplyAction="http://tempuri.org/IService/AlreadyRegisteredResponse")]
        System.Threading.Tasks.Task<bool> AlreadyRegisteredAsync(string codice_fiscale, string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConvalidLogIn", ReplyAction="http://tempuri.org/IService/ConvalidLogInResponse")]
        bool ConvalidLogIn(string mail, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConvalidLogIn", ReplyAction="http://tempuri.org/IService/ConvalidLogInResponse")]
        System.Threading.Tasks.Task<bool> ConvalidLogInAsync(string mail, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserByEmail", ReplyAction="http://tempuri.org/IService/GetUserByEmailResponse")]
        WebGymTrivelloniBattaglioli.ServiceReferenceWCF.UserDTO GetUserByEmail(string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserByEmail", ReplyAction="http://tempuri.org/IService/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.UserDTO> GetUserByEmailAsync(string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserActiveContract", ReplyAction="http://tempuri.org/IService/GetUserActiveContractResponse")]
        WebGymTrivelloniBattaglioli.ServiceReferenceWCF.ContractDTO GetUserActiveContract(string codice_fiscale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserActiveContract", ReplyAction="http://tempuri.org/IService/GetUserActiveContractResponse")]
        System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.ContractDTO> GetUserActiveContractAsync(string codice_fiscale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CercaClientiAssociatiAlTrainer", ReplyAction="http://tempuri.org/IService/CercaClientiAssociatiAlTrainerResponse")]
        WebGymTrivelloniBattaglioli.ServiceReferenceWCF.UserDTO[] CercaClientiAssociatiAlTrainer(string cod_fiscale_trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CercaClientiAssociatiAlTrainer", ReplyAction="http://tempuri.org/IService/CercaClientiAssociatiAlTrainerResponse")]
        System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.UserDTO[]> CercaClientiAssociatiAlTrainerAsync(string cod_fiscale_trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSchedeUtente", ReplyAction="http://tempuri.org/IService/GetSchedeUtenteResponse")]
        WebGymTrivelloniBattaglioli.ServiceReferenceWCF.SchedaDTO[] GetSchedeUtente(string cod_fiscale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSchedeUtente", ReplyAction="http://tempuri.org/IService/GetSchedeUtenteResponse")]
        System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.SchedaDTO[]> GetSchedeUtenteAsync(string cod_fiscale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InserisciSchedaNelDB", ReplyAction="http://tempuri.org/IService/InserisciSchedaNelDBResponse")]
        bool InserisciSchedaNelDB(string titolo, int durata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InserisciSchedaNelDB", ReplyAction="http://tempuri.org/IService/InserisciSchedaNelDBResponse")]
        System.Threading.Tasks.Task<bool> InserisciSchedaNelDBAsync(string titolo, int durata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AggiornaUtilizzoSchede", ReplyAction="http://tempuri.org/IService/AggiornaUtilizzoSchedeResponse")]
        bool AggiornaUtilizzoSchede(string cod_fiscale_trainer, string cod_fiscale_cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AggiornaUtilizzoSchede", ReplyAction="http://tempuri.org/IService/AggiornaUtilizzoSchedeResponse")]
        System.Threading.Tasks.Task<bool> AggiornaUtilizzoSchedeAsync(string cod_fiscale_trainer, string cod_fiscale_cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OttieniIdUtimaSchedaInserita", ReplyAction="http://tempuri.org/IService/OttieniIdUtimaSchedaInseritaResponse")]
        int OttieniIdUtimaSchedaInserita();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OttieniIdUtimaSchedaInserita", ReplyAction="http://tempuri.org/IService/OttieniIdUtimaSchedaInseritaResponse")]
        System.Threading.Tasks.Task<int> OttieniIdUtimaSchedaInseritaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AggiungiNuovaAssegnazione", ReplyAction="http://tempuri.org/IService/AggiungiNuovaAssegnazioneResponse")]
        bool AggiungiNuovaAssegnazione(string cod_fiscale_trainer, string cod_fiscale_cliente, int idScheda, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AggiungiNuovaAssegnazione", ReplyAction="http://tempuri.org/IService/AggiungiNuovaAssegnazioneResponse")]
        System.Threading.Tasks.Task<bool> AggiungiNuovaAssegnazioneAsync(string cod_fiscale_trainer, string cod_fiscale_cliente, int idScheda, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddNewExerciseToCardGym", ReplyAction="http://tempuri.org/IService/AddNewExerciseToCardGymResponse")]
        bool AddNewExerciseToCardGym(int id_scheda, string descrizione, int num_ripetizioni, System.TimeSpan tempo_recupero, string commento, string immagine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddNewExerciseToCardGym", ReplyAction="http://tempuri.org/IService/AddNewExerciseToCardGymResponse")]
        System.Threading.Tasks.Task<bool> AddNewExerciseToCardGymAsync(int id_scheda, string descrizione, int num_ripetizioni, System.TimeSpan tempo_recupero, string commento, string immagine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OttieniEserciziAssociatiAllaScheda", ReplyAction="http://tempuri.org/IService/OttieniEserciziAssociatiAllaSchedaResponse")]
        WebGymTrivelloniBattaglioli.ServiceReferenceWCF.OttieniEserciziAssociatiAllaSchedaResponse OttieniEserciziAssociatiAllaScheda(WebGymTrivelloniBattaglioli.ServiceReferenceWCF.OttieniEserciziAssociatiAllaSchedaRequest request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione presenta più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OttieniEserciziAssociatiAllaScheda", ReplyAction="http://tempuri.org/IService/OttieniEserciziAssociatiAllaSchedaResponse")]
        System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.OttieniEserciziAssociatiAllaSchedaResponse> OttieniEserciziAssociatiAllaSchedaAsync(WebGymTrivelloniBattaglioli.ServiceReferenceWCF.OttieniEserciziAssociatiAllaSchedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllExercise", ReplyAction="http://tempuri.org/IService/GetAllExerciseResponse")]
        WebGymTrivelloniBattaglioli.ServiceReferenceWCF.EsercizioDTO[] GetAllExercise();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllExercise", ReplyAction="http://tempuri.org/IService/GetAllExerciseResponse")]
        System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.EsercizioDTO[]> GetAllExerciseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddExerciseToCardGym", ReplyAction="http://tempuri.org/IService/AddExerciseToCardGymResponse")]
        bool AddExerciseToCardGym(string descrizione_esercizio, int id_scheda, int num_ripetizioni, System.TimeSpan tempo_recupero, string commento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddExerciseToCardGym", ReplyAction="http://tempuri.org/IService/AddExerciseToCardGymResponse")]
        System.Threading.Tasks.Task<bool> AddExerciseToCardGymAsync(string descrizione_esercizio, int id_scheda, int num_ripetizioni, System.TimeSpan tempo_recupero, string commento);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OttieniEserciziAssociatiAllaScheda", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OttieniEserciziAssociatiAllaSchedaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id_scheda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WebGymTrivelloniBattaglioli.ServiceReferenceWCF.EsercizioDTO[] lista_esercizi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public WebGymTrivelloniBattaglioli.ServiceReferenceWCF.CaratteristicaEsercizioDTO[] lista_caratteristiche;
        
        public OttieniEserciziAssociatiAllaSchedaRequest() {
        }
        
        public OttieniEserciziAssociatiAllaSchedaRequest(int id_scheda, WebGymTrivelloniBattaglioli.ServiceReferenceWCF.EsercizioDTO[] lista_esercizi, WebGymTrivelloniBattaglioli.ServiceReferenceWCF.CaratteristicaEsercizioDTO[] lista_caratteristiche) {
            this.id_scheda = id_scheda;
            this.lista_esercizi = lista_esercizi;
            this.lista_caratteristiche = lista_caratteristiche;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OttieniEserciziAssociatiAllaSchedaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OttieniEserciziAssociatiAllaSchedaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool OttieniEserciziAssociatiAllaSchedaResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WebGymTrivelloniBattaglioli.ServiceReferenceWCF.EsercizioDTO[] lista_esercizi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public WebGymTrivelloniBattaglioli.ServiceReferenceWCF.CaratteristicaEsercizioDTO[] lista_caratteristiche;
        
        public OttieniEserciziAssociatiAllaSchedaResponse() {
        }
        
        public OttieniEserciziAssociatiAllaSchedaResponse(bool OttieniEserciziAssociatiAllaSchedaResult, WebGymTrivelloniBattaglioli.ServiceReferenceWCF.EsercizioDTO[] lista_esercizi, WebGymTrivelloniBattaglioli.ServiceReferenceWCF.CaratteristicaEsercizioDTO[] lista_caratteristiche) {
            this.OttieniEserciziAssociatiAllaSchedaResult = OttieniEserciziAssociatiAllaSchedaResult;
            this.lista_esercizi = lista_esercizi;
            this.lista_caratteristiche = lista_caratteristiche;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WebGymTrivelloniBattaglioli.ServiceReferenceWCF.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.IService>, WebGymTrivelloniBattaglioli.ServiceReferenceWCF.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InserisciCliente(string codice_fiscale, string nome, string cognome, string mail, string data_nascita, string telefono, string password, string sesso) {
            return base.Channel.InserisciCliente(codice_fiscale, nome, cognome, mail, data_nascita, telefono, password, sesso);
        }
        
        public System.Threading.Tasks.Task<bool> InserisciClienteAsync(string codice_fiscale, string nome, string cognome, string mail, string data_nascita, string telefono, string password, string sesso) {
            return base.Channel.InserisciClienteAsync(codice_fiscale, nome, cognome, mail, data_nascita, telefono, password, sesso);
        }
        
        public WebGymTrivelloniBattaglioli.ServiceReferenceWCF.ContractDTO[] GetAvailableContracts() {
            return base.Channel.GetAvailableContracts();
        }
        
        public System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.ContractDTO[]> GetAvailableContractsAsync() {
            return base.Channel.GetAvailableContractsAsync();
        }
        
        public bool AddContractToClient(int id, string codice_fiscale, string startDate) {
            return base.Channel.AddContractToClient(id, codice_fiscale, startDate);
        }
        
        public System.Threading.Tasks.Task<bool> AddContractToClientAsync(int id, string codice_fiscale, string startDate) {
            return base.Channel.AddContractToClientAsync(id, codice_fiscale, startDate);
        }
        
        public bool CercaPersonalTrainerNelDB(string email, string password) {
            return base.Channel.CercaPersonalTrainerNelDB(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> CercaPersonalTrainerNelDBAsync(string email, string password) {
            return base.Channel.CercaPersonalTrainerNelDBAsync(email, password);
        }
        
        public bool AlreadyRegistered(string codice_fiscale, string mail) {
            return base.Channel.AlreadyRegistered(codice_fiscale, mail);
        }
        
        public System.Threading.Tasks.Task<bool> AlreadyRegisteredAsync(string codice_fiscale, string mail) {
            return base.Channel.AlreadyRegisteredAsync(codice_fiscale, mail);
        }
        
        public bool ConvalidLogIn(string mail, string password) {
            return base.Channel.ConvalidLogIn(mail, password);
        }
        
        public System.Threading.Tasks.Task<bool> ConvalidLogInAsync(string mail, string password) {
            return base.Channel.ConvalidLogInAsync(mail, password);
        }
        
        public WebGymTrivelloniBattaglioli.ServiceReferenceWCF.UserDTO GetUserByEmail(string mail) {
            return base.Channel.GetUserByEmail(mail);
        }
        
        public System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.UserDTO> GetUserByEmailAsync(string mail) {
            return base.Channel.GetUserByEmailAsync(mail);
        }
        
        public WebGymTrivelloniBattaglioli.ServiceReferenceWCF.ContractDTO GetUserActiveContract(string codice_fiscale) {
            return base.Channel.GetUserActiveContract(codice_fiscale);
        }
        
        public System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.ContractDTO> GetUserActiveContractAsync(string codice_fiscale) {
            return base.Channel.GetUserActiveContractAsync(codice_fiscale);
        }
        
        public WebGymTrivelloniBattaglioli.ServiceReferenceWCF.UserDTO[] CercaClientiAssociatiAlTrainer(string cod_fiscale_trainer) {
            return base.Channel.CercaClientiAssociatiAlTrainer(cod_fiscale_trainer);
        }
        
        public System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.UserDTO[]> CercaClientiAssociatiAlTrainerAsync(string cod_fiscale_trainer) {
            return base.Channel.CercaClientiAssociatiAlTrainerAsync(cod_fiscale_trainer);
        }
        
        public WebGymTrivelloniBattaglioli.ServiceReferenceWCF.SchedaDTO[] GetSchedeUtente(string cod_fiscale) {
            return base.Channel.GetSchedeUtente(cod_fiscale);
        }
        
        public System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.SchedaDTO[]> GetSchedeUtenteAsync(string cod_fiscale) {
            return base.Channel.GetSchedeUtenteAsync(cod_fiscale);
        }
        
        public bool InserisciSchedaNelDB(string titolo, int durata) {
            return base.Channel.InserisciSchedaNelDB(titolo, durata);
        }
        
        public System.Threading.Tasks.Task<bool> InserisciSchedaNelDBAsync(string titolo, int durata) {
            return base.Channel.InserisciSchedaNelDBAsync(titolo, durata);
        }
        
        public bool AggiornaUtilizzoSchede(string cod_fiscale_trainer, string cod_fiscale_cliente) {
            return base.Channel.AggiornaUtilizzoSchede(cod_fiscale_trainer, cod_fiscale_cliente);
        }
        
        public System.Threading.Tasks.Task<bool> AggiornaUtilizzoSchedeAsync(string cod_fiscale_trainer, string cod_fiscale_cliente) {
            return base.Channel.AggiornaUtilizzoSchedeAsync(cod_fiscale_trainer, cod_fiscale_cliente);
        }
        
        public int OttieniIdUtimaSchedaInserita() {
            return base.Channel.OttieniIdUtimaSchedaInserita();
        }
        
        public System.Threading.Tasks.Task<int> OttieniIdUtimaSchedaInseritaAsync() {
            return base.Channel.OttieniIdUtimaSchedaInseritaAsync();
        }
        
        public bool AggiungiNuovaAssegnazione(string cod_fiscale_trainer, string cod_fiscale_cliente, int idScheda, string data) {
            return base.Channel.AggiungiNuovaAssegnazione(cod_fiscale_trainer, cod_fiscale_cliente, idScheda, data);
        }
        
        public System.Threading.Tasks.Task<bool> AggiungiNuovaAssegnazioneAsync(string cod_fiscale_trainer, string cod_fiscale_cliente, int idScheda, string data) {
            return base.Channel.AggiungiNuovaAssegnazioneAsync(cod_fiscale_trainer, cod_fiscale_cliente, idScheda, data);
        }
        
        public bool AddNewExerciseToCardGym(int id_scheda, string descrizione, int num_ripetizioni, System.TimeSpan tempo_recupero, string commento, string immagine) {
            return base.Channel.AddNewExerciseToCardGym(id_scheda, descrizione, num_ripetizioni, tempo_recupero, commento, immagine);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewExerciseToCardGymAsync(int id_scheda, string descrizione, int num_ripetizioni, System.TimeSpan tempo_recupero, string commento, string immagine) {
            return base.Channel.AddNewExerciseToCardGymAsync(id_scheda, descrizione, num_ripetizioni, tempo_recupero, commento, immagine);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebGymTrivelloniBattaglioli.ServiceReferenceWCF.OttieniEserciziAssociatiAllaSchedaResponse WebGymTrivelloniBattaglioli.ServiceReferenceWCF.IService.OttieniEserciziAssociatiAllaScheda(WebGymTrivelloniBattaglioli.ServiceReferenceWCF.OttieniEserciziAssociatiAllaSchedaRequest request) {
            return base.Channel.OttieniEserciziAssociatiAllaScheda(request);
        }
        
        public bool OttieniEserciziAssociatiAllaScheda(int id_scheda, ref WebGymTrivelloniBattaglioli.ServiceReferenceWCF.EsercizioDTO[] lista_esercizi, ref WebGymTrivelloniBattaglioli.ServiceReferenceWCF.CaratteristicaEsercizioDTO[] lista_caratteristiche) {
            WebGymTrivelloniBattaglioli.ServiceReferenceWCF.OttieniEserciziAssociatiAllaSchedaRequest inValue = new WebGymTrivelloniBattaglioli.ServiceReferenceWCF.OttieniEserciziAssociatiAllaSchedaRequest();
            inValue.id_scheda = id_scheda;
            inValue.lista_esercizi = lista_esercizi;
            inValue.lista_caratteristiche = lista_caratteristiche;
            WebGymTrivelloniBattaglioli.ServiceReferenceWCF.OttieniEserciziAssociatiAllaSchedaResponse retVal = ((WebGymTrivelloniBattaglioli.ServiceReferenceWCF.IService)(this)).OttieniEserciziAssociatiAllaScheda(inValue);
            lista_esercizi = retVal.lista_esercizi;
            lista_caratteristiche = retVal.lista_caratteristiche;
            return retVal.OttieniEserciziAssociatiAllaSchedaResult;
        }
        
        public System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.OttieniEserciziAssociatiAllaSchedaResponse> OttieniEserciziAssociatiAllaSchedaAsync(WebGymTrivelloniBattaglioli.ServiceReferenceWCF.OttieniEserciziAssociatiAllaSchedaRequest request) {
            return base.Channel.OttieniEserciziAssociatiAllaSchedaAsync(request);
        }
        
        public WebGymTrivelloniBattaglioli.ServiceReferenceWCF.EsercizioDTO[] GetAllExercise() {
            return base.Channel.GetAllExercise();
        }
        
        public System.Threading.Tasks.Task<WebGymTrivelloniBattaglioli.ServiceReferenceWCF.EsercizioDTO[]> GetAllExerciseAsync() {
            return base.Channel.GetAllExerciseAsync();
        }
        
        public bool AddExerciseToCardGym(string descrizione_esercizio, int id_scheda, int num_ripetizioni, System.TimeSpan tempo_recupero, string commento) {
            return base.Channel.AddExerciseToCardGym(descrizione_esercizio, id_scheda, num_ripetizioni, tempo_recupero, commento);
        }
        
        public System.Threading.Tasks.Task<bool> AddExerciseToCardGymAsync(string descrizione_esercizio, int id_scheda, int num_ripetizioni, System.TimeSpan tempo_recupero, string commento) {
            return base.Channel.AddExerciseToCardGymAsync(descrizione_esercizio, id_scheda, num_ripetizioni, tempo_recupero, commento);
        }
    }
}
